"""The AgentRuntimeAdapter protocol — spec §10, verbatim."""
from __future__ import annotations

from typing import Protocol

from contracts.runtime import Checkpoint, RunContext, RunHandle, RunResult


class AgentRuntimeAdapter(Protocol):
    async def initialize_run(self, context: RunContext) -> RunHandle: ...
    async def execute(self, handle: RunHandle) -> RunResult: ...
    async def checkpoint(self, handle: RunHandle) -> Checkpoint: ...
    async def resume(self, checkpoint: Checkpoint) -> RunResult: ...
    async def cancel(self, handle: RunHandle) -> None: ...
